[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "fold"] }
quote = "1"

[dev-dependencies]

insta = "*"
